STM32CUBE_DIRECTORY := stm32cube
STM32CUBE_DOWNLOAD_DIRECTORY := stm32cube_download
STM32CUBE_EXECUTABLE := $(STM32CUBE_DIRECTORY)/STM32CubeMX
STM32CUBE_TAR_BZ2 := /tmp/stm32cube.tar.bz2
STM32CUBE_TAR := /tmp/stm32cube.tar

all: $(STM32CUBE_EXECUTABLE)

$(STM32CUBE_EXECUTABLE):
	rm -f $(STM32CUBE_TAR_BZ2) $(STM32CUBE_TAR)
	cat $(STM32CUBE_DOWNLOAD_DIRECTORY)/* > $(STM32CUBE_TAR_BZ2)
	(cd /tmp ; bunzip2 $(STM32CUBE_TAR_BZ2) )
	rm -rf $(STMCUBE_DIRECTORY)
	tar -x -f $(STM32CUBE_TAR)
	rm $(STM32CUBE_TAR)
